"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true


format = "$all"
#format = "$directory$all$character"

[hostname]
ssh_only=false
format='[$hostname]($style)[\]](bold yellow)'
style="bold purple"

[username]
show_always=true
format='[\[](bold yellow)[$user]($style)[ @ ](bold yellow)'
style_user="bold blue"

[directory]
truncation_length = 2
truncate_to_repo = true # truncates directory to root folder if in github repo
format='[\[📂️ $path\] ]($style)[$read_only]($read_only_style)'
#style = "bold italic #87A752"

[git_branch]
format='[\[$symbol$branch(:$remote_branch)\]]($style)'

[git_status]
style= "bold blue"

[rust]
format = '[\[$symbol($version)\]]($style)'
symbol = " "
[package]
format='[\[$symbol$version\]]($style)'
#symbol = ''
symbol = ' '

[python]
format='[\[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\))\]]($style)'
symbol = " "
[vagrant]
format='[\[$symbol($version)\]]($style)'
disabled=true
[c]
format='[\[$symbol($version)\]]($style)'
detect_extensions=["c", "h", "cpp", "hpp"]

[git_metrics]
disabled=false
#format = '([\[+$added\]]($added_style))([\[-$deleted\]]($deleted_style) )'
#format = '(\[([+$added]($added_style))/([-$deleted]($deleted_style))\])("bold grey")'
format = '(\[([+$added]($added_style))/([-$deleted]($deleted_style))\])("#707070")'

[memory_usage]
threshold = 50
format = '[\[$symbol($ram_pct)\]](bold dimmed red)'
disabled = false
symbol = ''

[docker_context]
format = '([\[$symbol(&version)\]]($style)'
symbol = '🐳'
disabled = false
detect_files = ['docker-compose.yml', 'docker-compose.yaml', 'Dockerfile']

